# Generated by Django 5.0.4 on 2024-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
