# Generated by Django 5.0.4 on 2024-04-10 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('11620a13-e7d2-488f-9242-15ee8b6ca40a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
